/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { SimpleCoin } from "./SimpleCoin";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export { SimpleCoin__factory } from "./factories/SimpleCoin__factory";
